Module3 task1
htmlacademy-adaptive/1789463-pink-24 pull request #4
Opened 2021-12-05 13:53 UTC by MaxMad446

2021-12-05 16:20 UTC, what1s1ove requested changes

2021-12-05 16:20 UTC, what1s1ove commented on source/less/blocks/page.less
> +  font-family: "Open Sans", sans-serif;
нужно добавить безопасный шрифт

2021-12-05 16:20 UTC, what1s1ove commented on source/less/blocks/stats.less
> +@images: "../img/stats";
перенести это ко всем переменным

2021-12-05 16:20 UTC, what1s1ove commented on source/less/blocks/stats.less
> +  font-family: "Open Sans", sans-serif;
зачем тут ещё фонт, если есть общий на хедере?

2021-12-07 05:35 UTC, MaxMad446 commented on source/less/blocks/page.less
> +  font-family: "Open Sans", sans-serif;
Какой именно?

2021-12-07 05:36 UTC, MaxMad446 commented on source/less/blocks/stats.less
> +@images: "../img/stats";
в глобал кинуть? в отдельную less?

2021-12-07 05:36 UTC, MaxMad446 commented on source/less/blocks/stats.less
> +  font-family: "Open Sans", sans-serif;
убрал

2021-12-07 15:22 UTC, what1s1ove commented on source/less/blocks/stats.less
> +@images: "../img/stats";
в глобальную к переменным

2021-12-07 15:22 UTC, what1s1ove commented on source/less/blocks/stats.less
> +  font-family: "Open Sans", sans-serif;
гуд

2021-12-07 15:23 UTC, what1s1ove commented on source/less/blocks/page.less
> +  font-family: "Open Sans", sans-serif;
Который есть в системе, похож на Open Sans и без засечек

2021-12-08 04:01 UTC, MaxMad446 commented on source/less/blocks/page.less
> +  font-family: "Open Sans", sans-serif;
Какой именно? В изначальной же папке лежат шрифты для проекта. Кроме Open Sans(bold, light, normal) в woff2 и woff, там ничего нет.

2021-12-08 06:18 UTC, what1s1ove commented on source/less/blocks/page.less
> +  font-family: "Open Sans", sans-serif;
Тот который встроен в систему юзера. Всегда нужно задавать минимуму три шрифта - Основной шрифт, Веб-безопасный, Тип шрифта. Ты должен был это делать и на первом уровне верстки тоже.

Критерий - https://up.htmlacademy.ru/adaptive/24/criteries#b10

2021-12-09 03:04 UTC, MaxMad446 commented on source/less/blocks/page.less
> +  font-family: "Open Sans", sans-serif;
На первом уровне, давались шрифты и разрешалось пользоваться только ими.

2021-12-09 05:08 UTC, what1s1ove commented on source/less/blocks/page.less
> +  font-family: "Open Sans", sans-serif;
Оки, на этом потоке другие правила 👍

2021-12-10 03:25 UTC, what1s1ove approved these changes

2021-12-10 03:26 UTC, merged